apiVersion: v1
kind: ReplicationController
metadata:
  name: rest-contr
  labels:
    app: thesis
    role: backend
    tier: filesistem
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thesis
        role: backend
        tier: rest
    spec:
      containers:
      - name: thesis-rest
        image: djob195/thesis-rest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: ""
        - name: DBTYPE
          value: ""
        - name: USERDB
          value: ""
        - name: PASSWORDDB
          value: ""
        - name: PATHDB
          value: ""
        - name: PORTDB
          value: ""
        - name: NAMEDB
          value: ""
        - name: DBTYPE
          value: ""
        - name: CADUCIDAD_TOKEN
          value: ""
        - name: SEED
          value: ""
        - name: ADMINUSER
          value: ""
        - name: ADMINPASSWORD
          value: ""
        - name: DESDE
          value: ""
        - name: LIMITE
          value: ""
        ports:
        - containerPort: 8080
      volumes:
      - name: upload-filesistem
        emptyDir: {}