apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: thesis
    role: backend
    tier: rest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: thesis
    role: backend
    tier: rest